const mockData = [
  {
    id: 920,
    title: "EXPLORING THE POTENTIAL OF ARTIFICIAL INTELLIGENCE",
    authors: "Juan Dela Cruz, Maria Santos",
    submittedDate: "2024-05-14 10:07:23",
    status: "Queued",
    progress: "Review",
    section: "Research Articles",
    workflowUrl: "#",
  },
  {
    id: 919,
    title: "A SYSTEMATIC REVIEW ON EDUCATIONAL TECHNOLOGY",
    authors: "Ana Reyes, Pedro Garcia",
    submittedDate: "2024-05-14 09:45:10",
    status: "Under Review",
    progress: "Review",
    section: "Research Articles",
    workflowUrl: "#",
  },
  {
    id: 918,
    title: "DEVELOPMENT OF AN AI-BASED JOURNAL MONITORING SYSTEM",
    authors: "Michael Tan, Sarah Lee",
    submittedDate: "2024-05-14 08:21:33",
    status: "Queued",
    progress: "Initial Review",
    section: "Technology",
    workflowUrl: "#",
  },
  {
    id: 917,
    title: "ASSESSING THE IMPACT OF DIGITAL TRANSFORMATION",
    authors: "Linda Wilson",
    submittedDate: "2024-05-13 16:50:12",
    status: "Revisions",
    progress: "Revisions",
    section: "Education",
    workflowUrl: "#",
  },
  {
    id: 916,
    title: "AN ANALYSIS OF SUSTAINABLE DEVELOPMENT PRACTICES",
    authors: "Robert Brown, Emily Davis",
    submittedDate: "2024-05-13 14:32:05",
    status: "Accepted",
    progress: "Copyediting",
    section: "Environmental Science",
    workflowUrl: "#",
  },
  {
    id: 915,
    title: "DESIGN AND IMPLEMENTATION OF WEB-BASED SYSTEMS",
    authors: "James Wilson",
    submittedDate: "2024-05-13 11:15:47",
    status: "Published",
    progress: "Published",
    section: "Computer Science",
    workflowUrl: "#",
  },
];

export default mockData;